version: "3.9"

services:
  products_management:
    container_name: products_management
    image: api_crud
    build: .
    ports:
      - 5000:5000
    environment:
      - DB_USER=letlm
      - DB_HOST=dbs
      - DB=products_management
      - DB_PASSWORD=0708
      - DB_PORT=5432
    depends_on:
      - dbs

  dbs:
    container_name: dbs
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=letlm
      - POSTGRES_PASSWORD=0708
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  db_test:
    container_name: db_test
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=letlm
      - POSTGRES_PASSWORD=0708
      - POSTGRES_DB=tests_products
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
